### ISSUE TITLE
Pittsburgh quiet place

### ISSUE THREAD

**Issue by anthonyrgreen** [aupiff/places-quiet#12]
Commonplace Coffee — terrace only:
6736 Reynolds St, Pittsburgh, PA 15206

**Comment by aupiff** [comment]
Terrace only? Does that mean they play music inside? That's not a place quiet.

**Comment by timgalebach** [comment]
Who's going to Pittsburgh? My truck is getting repaired in Altoona, and I'll be down that way some later next month.

**Comment by aupiff** [comment]
Anthony was passing though Pittsburgh to visit our friend Jack. No plans to visit any time soon.

**Comment by aupiff** [comment]
Well, I should visit Jack and see how he's doing. Let me know when you're planning to go to Pittsburgh and I'll try to see you and Jack in the same visit. We'll verify that Commonplace Coffee is not a place quiet.
