### ISSUE TITLE
New locations

### ISSUE THREAD

**Issue by davidmerfield** [aupiff/places-quiet#6]
- [x] New Amity Diner on Madison
- [x] Burrito Mariachi
- [ ] Other Zabars on Madison

**Comment by aupiff** [comment]
Went into a few Zabar locations this weekend and heard music, we'll have to be very careful about this.

**Comment by davidmerfield** [comment]
- Trattoria ????
- Hong Kong Tokyo Food

**Comment by aupiff** [comment]
yep,

* Trattoria del arte near columbus circle
* Congee Village

**Comment by aupiff** [comment]
adding all of these in a forthcoming commit. done.
